### ISSUE TITLE
Unnecessary ratelimits

### ISSUE THREAD

**Issue by m8cx** [OverHash/supermarket-tracker#2]
countdown api does not have ratelimits

also u should multithread it fr fr

**Comment by OverHash** [comment]
Retrieving all prices across Countdown only takes a few seconds currently -- since prices don't change that often (every 2-3 days during the weekdays), performance is not a huge issue currently.

The application is already multithreaded through a shim tasks system (basically a MPMC, see the idea at a page like [here](https://ruspiro.github.io/ruspiro-async-book/03-04-mpmc-channel.html)) (see https://github.com/OverHash/supermarket-tracker/blob/a54b20e1011f82309f57628d8d52d02cc8e7d14a/src/main.rs#L16-L17 for configuration).

I need to better document the architecture of the tasks system, but it works like this:
- I start initially with say 12 tasks
- each of those tasks then adds 30 more tasks once they are done
- sometimes when i'm at 15/30 of the 2nd batch of tasks, I want to delete all the other 15 tasks

This can all be rewritten to use channels and be a bit more conventional at some point. Using [future streams](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.for_each_concurrent) is one possibility here (but currently it wants `Output` to be `()`, while I would want `Vec<Self::Item>` for new tasks to add).

---
I suppose you are talking about https://github.com/OverHash/supermarket-tracker/blob/a54b20e1011f82309f57628d8d52d02cc8e7d14a/src/countdown/get_products.rs#L169-L171 for the ratelimit stuff. Countdown used to have some limits here, perhaps I can look at lifting them a little bit (but as said before, with the current multithreading system, there's more than sufficient bandwith to get all prices in a few seconds).
